manifest:
  remotes:
    - name: nick
      url-base: https://github.com/nkearbey
  projects:
    - name: zmk
      remote: nick
      revision: init
      import: app/west.yml
  self:
    path: config
